name: Lint Code
on:
  push:
    branches: [main]  # Adjust to your desired branches

jobs:
  always_success:
    runs-on: ubuntu-latest
    steps:
    - name: Always Successful Step
      run: echo "This job always succeeds"
